In [4]:
import pandas as pd
import os
import datetime

In [5]:
# def datetime_range(start, end, delta):
#     current = start
#     while current < end:
#         yield current
#         current += delta

In [7]:
# dts = [dt.strftime('%Y-%m-%d T%H:%M Z') for dt in 
#        datetime_range(datetime.datetime(2016, 9, 1, 7), datetime.datetime(2016, 9, 1, 9+12), 
#        datetime.timedelta(minutes=15))]

# print(dts)

['2016-09-01 T07:00 Z', '2016-09-01 T07:15 Z', '2016-09-01 T07:30 Z', '2016-09-01 T07:45 Z', '2016-09-01 T08:00 Z', '2016-09-01 T08:15 Z', '2016-09-01 T08:30 Z', '2016-09-01 T08:45 Z', '2016-09-01 T09:00 Z', '2016-09-01 T09:15 Z', '2016-09-01 T09:30 Z', '2016-09-01 T09:45 Z', '2016-09-01 T10:00 Z', '2016-09-01 T10:15 Z', '2016-09-01 T10:30 Z', '2016-09-01 T10:45 Z', '2016-09-01 T11:00 Z', '2016-09-01 T11:15 Z', '2016-09-01 T11:30 Z', '2016-09-01 T11:45 Z', '2016-09-01 T12:00 Z', '2016-09-01 T12:15 Z', '2016-09-01 T12:30 Z', '2016-09-01 T12:45 Z', '2016-09-01 T13:00 Z', '2016-09-01 T13:15 Z', '2016-09-01 T13:30 Z', '2016-09-01 T13:45 Z', '2016-09-01 T14:00 Z', '2016-09-01 T14:15 Z', '2016-09-01 T14:30 Z', '2016-09-01 T14:45 Z', '2016-09-01 T15:00 Z', '2016-09-01 T15:15 Z', '2016-09-01 T15:30 Z', '2016-09-01 T15:45 Z', '2016-09-01 T16:00 Z', '2016-09-01 T16:15 Z', '2016-09-01 T16:30 Z', '2016-09-01 T16:45 Z', '2016-09-01 T17:00 Z', '2016-09-01 T17:15 Z', '2016-09-01 T17:30 Z', '2016-09-01 T17:45 Z', '2016-09-01 T18:00 Z', '2016-09-01 T18:15 Z', '2016-09-01 T18:30 Z', '2016-09-01 T18:45 Z', '2016-09-01 T19:00 Z', '2016-09-01 T19:15 Z', '2016-09-01 T19:30 Z', '2016-09-01 T19:45 Z', '2016-09-01 T20:00 Z', '2016-09-01 T20:15 Z', '2016-09-01 T20:30 Z', '2016-09-01 T20:45 Z']

In [9]:
wind_df.iloc[0]['INTERVAL_ENDING']

Timestamp('2021-08-10 23:00:00')

In [3]:
# wind data
wind_folder = r'C:\Users\still\Documents\Github\NSF-1923278-Stochastic-Uncertainty-Management\Data\RawData\DownloadedFromERCOT\WindData'
windfiles = os.listdir(wind_folder)
wind_df = pd.DataFrame()
for file in windfiles:
    df = pd.read_csv(os.path.join(wind_folder,file),parse_dates=['INTERVAL_ENDING'])
    wind_df = pd.concat([wind_df, df])

wind_df = wind_df.sort_values(by='INTERVAL_ENDING')

In [ ]:
# drop duplicates

In [ ]:
wind_df.to_csv('wind_time_series.csv', index=False)

In [35]:
# load data
load_folder = r'C:\Users\still\Documents\Github\NSF-1923278-Stochastic-Uncertainty-Management\Data\RawData\DownloadedFromERCOT\LoadData'
loadfiles = os.listdir(load_folder)
load_df = pd.DataFrame()
for file in loadfiles:
#     print(file)
    df = pd.read_csv(os.path.join(load_folder,file),parse_dates=['IntervalEnding'])
    load_df = pd.concat([load_df, df])

load_df.sort_values(by='IntervalEnding')
# load_df.to_csv('load_time_series.csv', index=False)

,IntervalEnding,Coast,East,FarWest,North,NorthCentral,SouthCentral,Southern,West,SystemTotal,Model,InUseFlag,DSTFlag
0,2021-08-10 22:05:00,17165.099609,2226.379883,4335.029785,1685.400024,19596.000000,9795.620117,4605.560059,1804.810059,61213.898438,E,Y,N
1,2021-08-10 22:05:00,17180.312500,2231.569580,4338.073242,1682.538208,19639.021484,9809.599609,4614.828613,1807.504150,61303.449219,A6,N,N
2,2021-08-10 22:10:00,17061.500000,2202.959961,4329.979980,1674.880005,19454.099609,9718.580078,4576.620117,1791.680054,60810.300781,E,Y,N
3,2021-08-10 22:10:00,17094.734375,2219.791992,4331.342773,1672.571289,19510.753906,9748.837891,4594.126465,1798.882324,60971.039062,A6,N,N
4,2021-08-10 22:15:00,17009.658203,2207.963623,4324.676270,1662.732300,19383.375000,9687.746094,4573.307129,1790.207275,60639.667969,A6,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...
43,2021-08-12 01:50:00,13307.799805,1726.050049,4106.459961,1330.349976,15201.799805,7727.750000,3669.639893,1438.510010,48508.359375,E,Y,N
44,2021-08-12 01:55:00,13268.500000,1719.589966,4100.339844,1325.890015,15135.500000,7698.290039,3655.020020,1435.209961,48338.339844,E,Y,N
45,2021-08-12 01:55:00,13467.688477,1679.023438,4047.041504,1273.626099,15388.989258,7727.485352,3693.813477,1423.244507,48700.914062,A6,N,N
46,2021-08-12 02:00:00,13432.074219,1673.783203,4042.748535,1268.640137,15332.405273,7702.957031,3682.031738,1421.161377,48555.800781,A6,N,N
47,2021-08-12 02:00:00,13230.900391,1711.829956,4094.820068,1321.550049,15069.900391,7664.640137,3640.750000,1431.579956,48165.968750,E,Y,N

In [36]:
load_E_df = load_df[load_df['Model']=='E']
load_E_df = load_E_df.sort_values(by='IntervalEnding')
load_A6_df = load_df[load_df['Model']=='A6']
load_A6_df = load_A6_df.sort_values(by='IntervalEnding')

In [37]:
load_E_df.to_csv('load_modelE_time_series.csv', index=False)
load_A6_df.to_csv('load_modelA6_time_series.csv', index=False)